### ISSUE TITLE
How do you delete a block?

### ISSUE THREAD

**Issue by coderextreme** [enjalot/blockbuilder#104]

**Comment by enjalot** [comment]
you can delete a block by going to the gist link and deleting it from there. the gist link is available at the top of the app, or you can just change the url of your block from `blockbuilder.org/username/gistId` to `gist.github.com/username/gistId`

**Comment by coderextreme** [comment]
I’m trying to delete this block. http://bl.ocks.org/coderextreme/1256f90d9eea80c52d3d <http://bl.ocks.org/coderextreme/1256f90d9eea80c52d3d>  gist is gone, but perhaps it’s cached in my browser?

John

**Comment by coderextreme** [comment]
Yep, it was cached in my browser.  Thanks for your help.

John

**Comment by enjalot** [comment]
actually bl.ocks has a 5 minute cache on the server. this can be slightly frustrating if you've updated your code and want to see it on blocks right away, but usually blockbuilder looks exactly the same anyway.

just FYI your bl.ocks user page also has about a 5 minute cache before it updates (in case you add a thumbnail or delete a gist and wonder why it isn't showing up).

**Comment by 4096void** [comment]
Thx.
