### ISSUE TITLE
auth timeout way to fast

### ISSUE THREAD

**Issue by enjalot** [enjalot/blockbuilder#108]
People have noticed they get logged out after a while and then when they try to save they get an auth error. The user should never be logged out while using the app, and I've often noticed i'm no longer logged in the next day.
It may be as simple as changing the session duration to something much longer

**Comment by georules** [comment]
I noticed that I've been getting logged out it seems daily.  The ttl for redis is 2 weeks and the cookie is valid for a year.  Could something be getting reset server side?

**Comment by enjalot** [comment]
this should be fixed now, the cookie maxAge was accidentally set to 1 day instead of 1 year, even though comment said otherwise... :)

**Comment by georules** [comment]
Wow, I just glanced at that without thinking.  Math is important, kids.
