### ISSUE TITLE
slider turning real numbers into natural numbers

### ISSUE THREAD

**Issue by stelt** [enjalot/blockbuilder#110]
When I have 0.0 in my code I want the slider to not go 1 .. 2 etc. (what I DO want when I have 0 in my code), but I want it to go 0.1 .. 0.2 etc
So smallest change is based on the last digit.
Which means 0.00 should give 0.01 ..  0.02  etc

**Comment by georules** [comment]
this is probably an issue for the inlet https://github.com/enjalot/Inlet  library

**Comment by enjalot** [comment]
:+1: for an interesting idea, but it should be added as an issue to the Inlet library that @georules linked to.
