### ISSUE TITLE
get blockbuilder mentioned in d3js Google Group description

### ISSUE THREAD

**Issue by stelt** [enjalot/blockbuilder#111]
I don't see it mentioned with the Google Group how to change the description.
If anyone knows ...

**Comment by enjalot** [comment]
Mike controls the google group description, I can try to ask him

**Comment by enjalot** [comment]
I'm going to close this for now, while increasing exposure of blockbuilder is something we would all benefit from I think marketing can be best figured out in the d3js slack or blockbuilder gitter chat :8ball:
