### ISSUE TITLE
Unused area when switching to side-by-side with window width > 1705px

### ISSUE THREAD

**Issue by leitzler** [enjalot/blockbuilder#112]
When I switch to side-by-side mode with a wide Chrome window (>1705 pixels), there is an empty area between the code view and the output view:
![capture](https://cloud.githubusercontent.com/assets/3111805/12431941/8eab8100-bef8-11e5-9b37-4b9fd3b8aa53.PNG)

If I "grab" the blue bar, the code window snaps into place directly (and cannot be moved):
![capture2](https://cloud.githubusercontent.com/assets/3111805/12431999/f4c36fca-bef8-11e5-8c0e-7d9d8a0d9582.PNG)

It would be nice if the code window filled out that empty space without interaction when switching to side-by-side.

Running Chrome 47 on Windows 7.

**Comment by enjalot** [comment]
this was fixed with the recent commit and this code
https://github.com/enjalot/blockbuilder/blob/master/public/js/components/editor.js#L60

thanks!
