### ISSUE TITLE
Lock after fork does not work

### ISSUE THREAD

**Issue by espinielli** [enjalot/blockbuilder#115]
After I fork a bl.ock when I click on the lock to make it private nothing happens.
I do not find anything in the console.

PS: I am regularly and successfully logged in with Gihub accout.

**Comment by leitzler** [comment]
It is probably since the Github API doesn't support locking after a gist has been created.

**Comment by enjalot** [comment]
indeed it is a limitation of the GitHub API. Perhaps we could make the lock icon link to the edit page of the gist so that you can manually change it to private/public via the gist webpage.

**Comment by espinielli** [comment]
That's what I manually do to lock my newly forked bl.ock...
I was assuming the action was possible, so maybe you could have a different
visual clue associated with the lock icon... Make it flat (to signify R/O)
while instead make fork/save more 3D like buttons (to signify action)...
Thanks
