### ISSUE TITLE
clicking blocks link gives me old version

### ISSUE THREAD

**Issue by stelt** [enjalot/blockbuilder#123]
Happens on http://blockbuilder.org/stelt/611aa3f3b786eb9c0408
Can I do something browser-side to help it as long as this is not fixed? ctrl-F5 didn't work

**Comment by enjalot** [comment]
this is because bl.ocks.org has a 5 minute server-side cache. There isn't anything we can do about it except wait.

**Comment by stelt** [comment]
Sure felt longer, but feelings deceive. Glad to know this now.
maybe a hover text on the link: "takes few minutes to synch" ?
