### ISSUE TITLE
favicon; with suggestion

### ISSUE THREAD

**Issue by stelt** [enjalot/blockbuilder#124]
http://survivalcraftgame.wikia.com/wiki/Brick_Stairs
It says on the page: "Content is available under CC-BY-SA."

Reply that you like it and I'll turn it into the right format

**Comment by enjalot** [comment]
its definitely evocative of building blocks :)
I was thinking of maybe something a bit more flat and geometric for the logo, but I'm fine with doing this for the favicon for now. I think its nice to be able to differentiate tabs a little. With a favicon we can remove the Building Blocks from the <title> to make more room for the name of the block

**Comment by stelt** [comment]
as github doesn't allow a .ico here, I zipped it.
[favicon.zip](https://github.com/enjalot/blockbuilder/files/129940/favicon.zip)

**Comment by stelt** [comment]
@enjalot if assigning an issue to someone only means putting a prominent reminder somewhere, go ahead and assign this to me. Then at some point I'll turn the file in the above comment in a proper Pull Request. #notAGithubRegular :-)

**Comment by enjalot** [comment]
I don't think assigning helps with reminding, but I would love a proper PR. Happy to guide you through it! I've been meaning to get to some issues but contract work has been swamping me

**Comment by georules** [comment]
@stelt My suspicion is that if you put the file in public/ that express static will pick it up (https://github.com/enjalot/blockbuilder/blob/master/server.js#L24).  git add, commit and push to your fork & pull request.

**Comment by stelt** [comment]
@georules read your comment, agreed, but just as I started to make it so, 2 questions came up about CC-BY-SA:
1 is blockbuilder compatible licence-wise? If yes ...
...2 where should the BY be mentioned?

**Comment by georules** [comment]
Blockbuilder's code is a 3-clause BSD - the art you are adding with CC-BY-SA should not pose a conflict, especially as it is a different work, they are not 're-mixed' or dependent on each other.  We just need to be specific as to what work is related to what license.  

You could append the BY for that file in the LICENSE file, specifying the work's location in the project and appropriate credit.

**Comment by enjalot** [comment]
thanks for the PR @stelt!
