### ISSUE TITLE
data anonymization tool (link?)

### ISSUE THREAD

**Issue by steltenpower** [enjalot/blockbuilder#128]
I expect many wanting to use this tool, wanting to share there viz work and cooperate, not being allowed to share the actual data. If you just want to use this tool and not share at all, a private repo would work

There is a workaround that could be made easier:
- Have different data that has the same 'shape' saved. (provide tooling, or a link to it, that helps in creating this fake/anonymized data)
- You can even put the actual data in, show the result, NOT press save and then ctrl-Z back to the fake data (maybe 'file' tabs with the real data, that overrule the actual real files saved on github with the fake data)

**Comment by georules** [comment]
How does the client render the real data without having access to that data?

What kind of tooling already exists for generating fake data from a private data set?  This sounds like an interesting project of its own.

**Comment by enjalot** [comment]
I think one way to solve this would be to make a desktop version of BB.
complete privacy.

as for a tool to make fake matching data, that is super interesting. i do
think it should start as an independent library/project. one could download
all the data for the indexed gists and test it on them.
400mb zip linked in this blog post
https://medium.com/@enjalot/searching-for-examples-2c0f75709c1a

**Comment by micahstubbs** [comment]
will consider this question answered and close this issue
