### ISSUE TITLE
Any non-javascript source type (e.g: type="text/jsx") are ignored by both the syntax highlighting and the render-pane

### ISSUE THREAD

**Issue by milroc** [enjalot/blockbuilder#129]
http://blockbuilder.org/milroc/5520449
http://blockbuilder.org/milroc/d22bbf92231876505e5d

**Comment by milroc** [comment]
http://blockbuilder.org/anonymous/60326be426ae8d022d35

**Comment by milroc** [comment]
This one works though: http://blockbuilder.org/anonymous/424e16c63d59ce2e2a37

**Comment by iansinnott** [comment]
:+1: It would be nice to be able to use ES6/Babel code with syntax highlighting.

**Comment by enjalot** [comment]
this would need to be supported in CodeMirror, which has an open issue https://github.com/codemirror/CodeMirror/issues/3122

**Comment by leitzler** [comment]
That issue is closed, but it still doesn't work for script type="text/babel". I've created a pull request to CodeMirror that adds that feature, https://github.com/codemirror/CodeMirror/pull/4118

As a workaround until that PR is merged (or if it isn't) you can add lang="babel" to your <script>-tag.

**Comment by enjalot** [comment]
The syntax highlighting aspect of this was closed by #160 thanks to @leitzler, the render frame problem is a deeper issue with how we are loading code into the iframe. I don't see a way around it for now.
A little more context on that problem (shown in the first two blocks) is that we are essentially copy pasting the content of each file into the index.html of the block before we put it in the iframe. This means that any code that contains something like `</script>` will break the functionality.
The workaround is to host any code like that externally so you can continue using the src attribute of a script tag as expected. In many cases this is fine, it looks like @milroc essentially uploaded a local dev folder. I would love to support that functionality but its hard to do.
