### ISSUE TITLE
[Feature Request] Support ES6 / Babel

### ISSUE THREAD

**Issue by iansinnott** [enjalot/blockbuilder#130]
It would be a nice feature if Blockbuilder supported ES6/Babel. Since not everyone is using ES6 I completely understand if this is beyond the scope of the project. However, for those of us that do prefer to write ES6 it would be nice if the editor at least supported syntax highlighting for script tags with arbitrary `type` attributes. Here's an example I created to demonstrate: http://blockbuilder.org/iansinnott/6aab4fa8c633358feabe

It should be noted that the code in that example does all run **just fine**, however, it's not ideal to code without syntax highlighting. 

This relates to #129.

**Comment by leitzler** [comment]
You could add lang="babel" in your script tag: <script lang="babel".. 

I've created a pull request to CodeMirror that will allow only defining type="text/babel", https://github.com/codemirror/CodeMirror/pull/4118

**Comment by iansinnott** [comment]
Awesome @leitzler, thanks. let's hope it gets merged.

**Comment by enjalot** [comment]
fixed with PR #160 thanks @leitzler!
