### ISSUE TITLE
missing index.html causes blockbuilder to hang

### ISSUE THREAD

**Issue by enjalot** [enjalot/blockbuilder#140]
http://blockbuilder.org/mbostock/9927735 hangs where
http://bl.ocks.org/mbostock/9927735 neatly displays “moved to another address”

**Comment by Fil** [comment]
with the follwing patch we will receive an explicit error message "Could not find index.html"

```
diff --git a/public/js/stores/gists.js b/public/js/stores/gists.js
index 9d79710..41db2e8 100644
--- a/public/js/stores/gists.js
+++ b/public/js/stores/gists.js
@@ -67,7 +67,7 @@ var GistsStore = Reflux.createStore({
     // making another fetch request if they look at the same gistId
     this.gistsById[data.gistId] = data.response;

-    var index = data.response.files["index.html"];
+    var index = data.response.files["index.html"] || { content: "" };
     index.content = stripRelativeBlock(index.content);

     this.trigger({
```

**Comment by micahstubbs** [comment]
verified that @Fil's patch works as described 

![screen shot 2017-05-11 at 1 27 26 pm](https://cloud.githubusercontent.com/assets/2119400/25970463/9a4f6c92-364d-11e7-81de-47f3cbebc2aa.png)
