### ISSUE TITLE
making something for alert()

### ISSUE THREAD

**Issue by Fil** [enjalot/blockbuilder#144]
would you agree to have a replacement for `alert()` in blockbuilder? they are forbidden in iframes.

even if it's not modal, but just so that copy/pasting snippets of code "works"

maybe something like https://gist.github.com/Fil/dec83591db1a0a560aad270da119f97a ; at a minimum we could have `alert=console.log`

**Comment by enjalot** [comment]
this could be achieved in [`parseCode.js`](https://github.com/enjalot/blockbuilder/blob/master/public/js/utils/parseCode.js) similar to the way we override xmlhttprequest

**Comment by Fil** [comment]
Thanks!

>

-- 
-- Fil
