### ISSUE TITLE
height is not defined

### ISSUE THREAD

**Issue by pavelloz** [enjalot/blockbuilder#158]
I added a comment here:
https://github.com/enjalot/blockbuilder/pull/156/files#diff-d544bdc7d5db2a3cec5b1e8ec6577f94R418

And after that i confirmed that this is in fact an error:
![height-error](https://cloud.githubusercontent.com/assets/546845/16872121/2776ddb2-4a8b-11e6-8ebf-e12f98c961e9.png)

**Comment by enjalot** [comment]
thanks! messed up copy pasting..
