### ISSUE TITLE
Slider in Chrome doesn't work

### ISSUE THREAD

**Issue by zukethenuke** [enjalot/blockbuilder#169]
Hi, I discovered blockbuilder yesterday, terrific site, I can't wait to use it!  I'm having one issue though, the little slider that pops up when you click on a number so you can adjust it, doesn't work in Chrome.  It pops up but won't slide.  It works fine if I open the site in Safari.  I tried disabling all my Chrome extensions and restarting the browser, but the slider still doesn't work.   Anyone have an idea or suggestion.  Thanks.

**Comment by georules** [comment]
What version of Chrome are you using?  OSX Chrome 51 is working for me.

This is actually a problem with Inlet - the library providing the slider.  Perhaps this is related to this issue recently posted: https://github.com/enjalot/Inlet/issues/32

**Comment by zukethenuke** [comment]
I'm using the new newest version of Chrome (Version 52.0.2743.116 (64-bit)).  You might be right about the library, because the slider doesn't work on either blockbuilder or tributary.  It's been a while since I've been to tributary, but I think it used to work for me there.   Thank you for the response.  Hopefully they get it fixed soon.  Cheers.

**Comment by georules** [comment]
Quick question: can you move the slider in this demo?
http://codepen.io/georules/pen/akQLQm

The inlet slider isn't much more than just an input type="range".  I wonder if chrome broke something 😨

**Comment by zukethenuke** [comment]
Yup, the slider on CodePen works the way it's supposed to.

I just tried the slider for adjusting color ranges on blockbuilder and it works fine in Chrome, it's only the slider for numbers that isn't working.

**Comment by enjalot** [comment]
this was a problem with the way new chrome was rendering the slider (basically hiding it) so the input event never fired. I fixed it by updating the style to make the input element itself fill up the div that holds the slider.
