### ISSUE TITLE
Consider exposing parseCode as a standalone library?

### ISSUE THREAD

**Issue by curran** [enjalot/blockbuilder#187]
Awesome work on Blockbuilder! I use it almost every day.

I have a project I'm working that needs to have the exactly the same functionality as is implemented in

https://github.com/enjalot/blockbuilder/blob/master/public/js/utils/parseCode.js

It would be interesting to consider making this available as a separate library. Or maybe it could be published inside the "building-blocks" NPM package, used via something like

```js
require("building-blocks/parseCode")
```

Here's what I'm using for now https://gist.github.com/curran/c19e1c8fd3428984255ae37be3162dc0 I manually copy-pasted the code through the [Babel REPL](https://babeljs.io/repl) to produce this. It's exposing a browser global `parseCode`.

Ideally the resulting module would be exposed as UMD. This might be possible to do by

 * adding an additional Webpack config that compiles parseCode.js into a standalone UMD module,
 * invoking the new Webpack config build step as an NPM prepublish script
 * publishing the "building-blocks" module to NPM.
 * voila, usage via `require("building-blocks/parseCode")` or `import parseCode from "building-blocks/parseCode"`

Let me know if there is any interest in this idea, I can try to create a PR with changes that could make it work.

**Comment by georules** [comment]
This is a great idea.  Having contributed to this part of the code, a major issue to address is this:

https://github.com/enjalot/blockbuilder/blob/master/public/js/utils/parseCode.js#L245

"lines" is used to properly offset the user-code from the template so that user-code error markers are placed in the right place.  The code for injecting the postMessage, which includes the lines value also needs to be included in this line count.

**Comment by curran** [comment]
@georules Interesting. Thanks for your input.

I suppose I'm more interested in a stripped down version that just makes the execution work. Debugging support is not a requirement for my particular use case, which is more of a "controlled environment" than Blockbuilder (where debugging support is clearly a priority).

I wonder if it might be worth trying to split up the "basic" version from the "advanced" version (which could ideally be layered on top of the "basic" version).

"basic" (what I'm interested in using) would include:

- [Support for .js files](https://github.com/enjalot/blockbuilder/blob/master/public/js/utils/parseCode.js#L41)
- [Support for .css files](https://github.com/enjalot/blockbuilder/blob/master/public/js/utils/parseCode.js#L74)
- [Support for short-circuited XHR (e.g. .csv, .json)](https://github.com/enjalot/blockbuilder/blob/master/public/js/utils/parseCode.js#L133)

"advanced" (what Blockbuilder needs) would include

 - [Error handling and the `postMessage` bit](https://github.com/enjalot/blockbuilder/blob/master/public/js/utils/parseCode.js#L245)
 - [Support for .xml files](https://github.com/enjalot/blockbuilder/blob/master/public/js/utils/parseCode.js#L140)
 - [Support for .coffee files](https://github.com/enjalot/blockbuilder/blob/master/public/js/utils/parseCode.js#L60)
 - [Handling of jQuery-specific CORS property](https://github.com/enjalot/blockbuilder/blob/master/public/js/utils/parseCode.js#L122)
 - [Mapbox-specific blob protocol](https://github.com/enjalot/blockbuilder/blob/master/public/js/utils/parseCode.js#L132)
 - [Alert override](https://github.com/enjalot/blockbuilder/blob/master/public/js/utils/parseCode.js#L238)

**Comment by curran** [comment]
So I went ahead and started in on making this a standalone module. Here's what I've got so far:

https://github.com/curran/magic-sandbox

I've tried to focus on giving credit where credit is due (@enjalot @georules @pavelloz @erikhazzard
), and I copied over the LICENSE from Blockbuilder. I'd even be happy to transfer ownership of the repo to @enjalot, to be a "sibling" of blockbuilder, if that would be preferred.

**Comment by curran** [comment]
Closing this, as I'm having success with the sandbox module outside of Blockbuilder. I've released it as [magic-sandbox](https://github.com/curran/magic-sandbox), and it's in use here [https://curran.github.io/d3-in-motion/#2/2/7](https://curran.github.io/d3-in-motion/#2/2/7) (from [curran/d3-in-motion](https://github.com/curran/d3-in-motion)).

It may be interesting to add `magic-sandbox` as a dependency to Blockbuilder, and add features there.
