### ISSUE TITLE
only block collection shown created before renaming of Github user

### ISSUE THREAD

**Issue by steltenpower** [enjalot/blockbuilder#190]
e.g. "stelt" (old) vs "steltenpower" (new)

**Comment by micahstubbs** [comment]
@steltenpower thanks for reporting this issue!  I know it was back in March - is there a screenshot that you can share?

**Comment by steltenpower** [comment]
At this moment there's nothing I see that I'm sure of that it's wrong

**Comment by micahstubbs** [comment]
☺
