### ISSUE TITLE
Adopt magic-sandbox

### ISSUE THREAD

**Issue by curran** [enjalot/blockbuilder#191]
This issue is about removing the file `parseCode.js`, and in its place using [https://github.com/curran/magic-sandbox](https://github.com/curran/magic-sandbox), which would be a new dependency. This should work fine, as magic-sandbox is derived originally from `parseCode.js`.

**Comment by georules** [comment]
❤️

**Comment by micahstubbs** [comment]
👍  for adopting `magic-sandbox`

this should happen after PR https://github.com/enjalot/blockbuilder/pull/194 is resolved, since it modifies `parseCode.js`
