### ISSUE TITLE
Renderer doesn't include DOCTYPE

### ISSUE THREAD

**Issue by ColinEberhardt** [enjalot/blockbuilder#192]
I've been hunting down an odd CSS-related issue, where the rendering within blockbulder and the bl.ocks website differs. I've managed to boil it down to block builder omitting the DOCTYPE. 

This block simply renders a big red square:

```
<!DOCTYPE html>
<div style="height:100%; background-color: red"/>
```

In block builder you can see the square filling the screen:

http://blockbuilder.org/ColinEberhardt/bcecc04f27f62acdf44fd350e166b24d

Whereas on the blocks website, the div has a height of zero:

https://bl.ocks.org/ColinEberhardt/bcecc04f27f62acdf44fd350e166b24d

Looking at the difference in the rendered output, here it is from bl.ocks:

![image](https://cloud.githubusercontent.com/assets/1098110/24708387/96f1f4da-1a0e-11e7-9a7a-456754fbd596.png)

And here is the iframe contents from block builder:

![image](https://cloud.githubusercontent.com/assets/1098110/24708428/bd0571d8-1a0e-11e7-85f3-1ca07e3e1870.png)

The difference is the lack of HTML5 DOCTYPE. I have confirmed that omitting the DOCTYPE from a HTML document has this effect,.

**Comment by enjalot** [comment]
Thanks for the detailed report!

So let me see if I understand, blockbuilder should also have a 0 height div
if it was automatically adding DOCTYPE in the renderer?
I guess the problem is the renderer needs to put the DOCTYPE at the top of
the compiled index.html for the user, since writing it in the editor will
put it below some other content we inject to make the live preview work.

**Comment by ColinEberhardt** [comment]
> Thanks for the detailed report!

No worries - was going to try and fix it, but looked at the setup instructions, and backed away on seeing 'brew install'!

> So let me see if I understand, blockbuilder should also have a 0 height div
> if it was automatically adding DOCTYPE in the renderer?

Correct, the div should be zero height. I guess that the omission of the DOCTYPE is causing the browser to render in a non-standard mode (it's a while since I looked at quirks mode, so not entirely sure what logic would be applied in the absence of any DOCTYPE)

By the way, I'm loving this tool - it really helped me with building this interactive, responsive small multiple plot for a blog post:

https://bl.ocks.org/ColinEberhardt/raw/3c780088c363d1515403f50a87a87121/

**Comment by micahstubbs** [comment]
able to reproduce this in my local blockbuilder dev environment
![screen shot 2017-05-04 at 3 30 13 pm](https://cloud.githubusercontent.com/assets/2119400/25727546/a92d0ffe-30de-11e7-91a4-a0d03355f54e.png)

**Comment by micahstubbs** [comment]
> I guess the problem is the renderer needs to put the DOCTYPE at the top of
the compiled index.html for the user, since writing it in the editor will
put it below some other content we inject to make the live preview work.

@enjalot curious, can you point us to the file where we compile that `index.html` for the user?

**Comment by enjalot** [comment]
@micahstubbs this is the main file where it happens: https://github.com/enjalot/blockbuilder/blob/master/public/js/utils/parseCode.js

its supposed to get migrated to @curran's https://github.com/curran/magic-sandbox at some point.

**Comment by micahstubbs** [comment]
ok, looks like this produces the desired behavior
![screen shot 2017-05-04 at 3 53 24 pm](https://cloud.githubusercontent.com/assets/2119400/25728141/0b8ab004-30e2-11e7-8ff9-bc54aaecd694.png)

**Comment by micahstubbs** [comment]
PR here https://github.com/enjalot/blockbuilder/pull/194 🎉
