### ISSUE TITLE
Default text styling is broken

### ISSUE THREAD

**Issue by ocarneiro** [enjalot/blockbuilder#204]
Example page (fresh block) is broken in Firefox. Text styling is done by svg.style, which works fine in Google Chrome, but have no effect in Firefox. Using svg.attr seems to work fine on both.
I will submit a fix shortly, but this issue should be a good place to discuss why it's broken.

**Comment by micahstubbs** [comment]
fixed in https://github.com/enjalot/blockbuilder/pull/205
