### ISSUE TITLE
.tsv url wrapper needed?

### ISSUE THREAD

**Issue by 35degrees** [enjalot/blockbuilder#207]
Hi Micah,

Do I need to add a wrapper to my URL to pull the .tsv data in?
http://blockbuilder.org/35degrees/54c9bd50e75cffc13acef3495844b361

The file works as an upload.

Thanks!

**Comment by enjalot** [comment]
Hi,
You need to enable CORS on your webserver so you can request the data from another domain
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS
we recommend the #blockbuilder channel on the d3js slack for these kinds of questions! you can join here: https://d3-slackin.herokuapp.com/
