### ISSUE TITLE
Make the site use HTTPS

### ISSUE THREAD

**Issue by ecgan** [enjalot/blockbuilder#217]
Apparently the site doesn't work when I use https://blockbuilder.org/ instead of http://blockbuilder.org/ .

I stumbled upon this when I was looking at a block at https://bl.ocks.org/mbostock/3887051 , and I manually changed the bl.ocks.org domain to blockbuilder.org domain while leaving the https intact.

**Comment by micahstubbs** [comment]
will take a look at this one

going to try to follow the instructions here 

1) https://letsencrypt.org/getting-started/
2) https://certbot.eff.org/lets-encrypt/ubuntuxenial-other

**Comment by micahstubbs** [comment]
this is complete 🎉 

https://blockbuilder.org
