### ISSUE TITLE
compatibility with d3 v5 / d3-fetch?

### ISSUE THREAD

**Issue by Fil** [enjalot/blockbuilder#218]
On blockbuilder http://blockbuilder.org/Fil/2a011c40f37f01117dc392012e80a935 fails to load the csv through d3-fetch / d3v5.

https://bl.ocks.org/Fil/2a011c40f37f01117dc392012e80a935 works.

Console:
![capture d ecran 2018-02-20 a 12 11 36](https://user-images.githubusercontent.com/7001/36421028-46469b1e-1637-11e8-98d4-9bb3850c9a60.png)

**Comment by enjalot** [comment]
this makes sense. the way we were supporting the v4 fetch was by overriding the AJAX object on the window.
I'm not sure what it will take to support this way of doing it. It should be doable but I doubt I'll have time/energy any time soon to fix it. perhaps @curran or @georules will have some ideas as they are familiar with the [magic-sandbox](https://github.com/curran/magic-sandbox) that handles the AJAX support for v3/v4

**Comment by curran** [comment]
It's funny, just today the same issue came up in Datavis.tech (cc @robcrock) , which also uses MagicSandbox, which I think is where support for `fetch` would need to be added.

Created a new issue over there https://github.com/curran/magic-sandbox/issues/7

**Comment by curran** [comment]
Idea: We add a polyfill for `fetch` that uses our already overridden XMLHttpRequest inside MagicSandbox (the idea is not my own - from user steve in D3 Slack).

Anyone know of a good small `fetch` polyfill?

**Comment by curran** [comment]
@enjalot @Fil @micahstubbs A fix has been implemented over at https://github.com/datavis-tech/magic-sandbox/pull/8 Your review there would be appreciated. Thanks!

**Comment by micahstubbs** [comment]
👍 commented here https://github.com/datavis-tech/magic-sandbox/pull/8#issuecomment-376327173
