### ISSUE TITLE
No longer able to define/change thumbnail.png

### ISSUE THREAD

**Issue by Kcnarf** [enjalot/blockbuilder#219]
A the moment, 23rd February 2018
 * [ ] when working on a fresh new project, GUI no longer proposes to view the 'thumbnail.png' file
 * [ ] when working on an old project and viewing an already existing 'thumbnail.png' file, GUI no longer proposes to upload a new image

**Comment by micahstubbs** [comment]
@Kcnarf thanks for the bug report!  I'm happy to review a PR if you figure out a way to fix this 😄

**Comment by Kcnarf** [comment]
As of 1st March 2018, none of the two use cases occur 👍

**Comment by micahstubbs** [comment]
@kcnarf curious, what changed for you on March 1st? ☺

**Comment by Kcnarf** [comment]
What changed for you on March 1st
=> it appears that I was logout when I depict the 2 use cases and post the issue

Both use cases appear when the user is not logged in, preventing to edit the bl.ock, which is absolutely the expected behaviour.

Adding and updating the 'preview.png' file is available when logged on.

Please pardon me for issuing this non-issue ...

**Comment by micahstubbs** [comment]
no problem, thanks for explaining 😄
