### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by micahstubbs** [enjalot/blockbuilder#226]
Uncaught SyntaxError: Unexpected token <

![screen shot 2018-09-28 at 11 30 40 am](https://user-images.githubusercontent.com/2119400/46226709-01185680-c312-11e8-897f-1d39ee8d8099.png)

**Comment by micahstubbs** [comment]
originally reported by @enjalot  in the d3 slack blockbuilder channel https://d3js.slack.com/archives/C0LBA67MG/p1538155876000100

![screen shot 2018-09-28 at 11 31 38 am](https://user-images.githubusercontent.com/2119400/46226761-2a38e700-c312-11e8-8fad-c44c58a42001.png)

**Comment by micahstubbs** [comment]
it looks like this bug was likely introduced in https://github.com/enjalot/blockbuilder/commit/c87c5b76b81fd0ea1066b3ce1e19637df0538e2b or https://github.com/enjalot/blockbuilder/commit/8002ddb8f2db87876e176d034d77e0f19321483b

**Comment by enjalot** [comment]
fixed with https://github.com/enjalot/blockbuilder/commit/dd26f556a38e832f1b63dad53cbec19f2b394d11

**Comment by micahstubbs** [comment]
fix verified 👍 

![screen shot 2018-09-29 at 10 04 07 pm](https://user-images.githubusercontent.com/2119400/46253574-c1499000-c433-11e8-810a-146c72cd0868.png)

https://blockbuilder.org/
