### ISSUE TITLE
Broken Auth Flow with HTTPS

### ISSUE THREAD

**Issue by curran** [enjalot/blockbuilder#227]
Something seems fishy about the auth flow at the moment. 

![image](https://user-images.githubusercontent.com/68416/46723605-dcb76500-cc95-11e8-8293-4998cfb46752.png)

Isolated this to `https` only. Authentication works fine with `http`, gives this error with `https`.

---

will add the bug report from @EE2dev as well - @micahstubbs 

I love to use blockbuilder and for me logging in through the github account works perfectly fine.
A friend of mine wanted to host a d3.js quiz I wrote, so I thought the easiest is
- he creates his own github account
- he just forkes my gist through blockbuilder
- he can adjust the code in blockbuilder

Logging on github works fine. But logging on blockbuilder.org through the github account leads to the following error:

![gh_bb](https://user-images.githubusercontent.com/7562919/48482725-c6ab4000-e811-11e8-8ad7-22213a3e1216.png)

![lnhmjjkcoaomllab](https://user-images.githubusercontent.com/7562919/48482568-500e4280-e811-11e8-81b1-a18778010fd9.png)

Do you need more than a github account to use blockbuilder and fork an existing gist? Do you need to have an existing github repo or a gist,..?!

**Comment by micahstubbs** [comment]
thanks for reporting this @curran 

it looks like we need to pass an `https` `redirect_uri` to github during the oauth dance for `https` sessions.

related to  #225  - if we redirect http to https, then I think we could just always use the https uri as the redirect_uri

**Comment by ymoran00** [comment]
Happened too - can't login.

**Comment by micahstubbs** [comment]
hoping to have some bandwidth to fix this one soon.

**Comment by enjalot** [comment]
Ok, I've updated the redirect link on the github app to use https. We should probably deploy the redirect to https @micahstubbs

**Comment by eduardosuela** [comment]
Still getting the Authentication error. Yikes  : ((

**Comment by eduardosuela** [comment]
@aurelient it works fine in https

**Comment by micahstubbs** [comment]
I like the idea of better error handling, and perhaps a FAQ entry too 💡

**Comment by micahstubbs** [comment]
ok redirecting http to https is fixed 🎉 https://github.com/enjalot/blockbuilder/issues/225

not quite out of the woods on this one though. @enjalot  when I click `login`, I see this error:

![screen shot 2018-12-02 at 11 52 21 pm](https://user-images.githubusercontent.com/2119400/49360250-7d6e4380-f68d-11e8-9be3-79babcee1359.png)

```javascript
AuthorizationError: The redirect_uri MUST match the registered callback URL for this application.
   at Strategy.OAuth2Strategy.authenticate (/home/ubuntu/blockbuilder/node_modules/passport-github/node_modules/passport-oauth2/lib/strategy.js:131:25)
   at attempt (/home/ubuntu/blockbuilder/node_modules/passport/lib/middleware/authenticate.js:348:16)
   at authenticate (/home/ubuntu/blockbuilder/node_modules/passport/lib/middleware/authenticate.js:349:7)
   at Layer.handle [as handle_request] (/home/ubuntu/blockbuilder/node_modules/express/lib/router/layer.js:95:5)
   at next (/home/ubuntu/blockbuilder/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/home/ubuntu/blockbuilder/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/home/ubuntu/blockbuilder/node_modules/express/lib/router/layer.js:95:5)
   at /home/ubuntu/blockbuilder/node_modules/express/lib/router/index.js:277:22
   at Function.process_params (/home/ubuntu/blockbuilder/node_modules/express/lib/router/index.js:330:12)
   at next (/home/ubuntu/blockbuilder/node_modules/express/lib/router/index.js:271:10)
```

**Comment by micahstubbs** [comment]
@enjalot curious, can you check/update the redirect link on the github app one more time?

**Comment by micahstubbs** [comment]
weird, in an incognito tab, the redirect link seems to work fine.  I see the github login page 🤔 

![Uploading Screen Shot 2018-12-02 at 11.57.30 PM.png…]()

**Comment by enjalot** [comment]
I got the error when I logged out and logged in again.
I'm wondering if we need to provide the full URI for the callbackURL here:
https://github.com/enjalot/blockbuilder/blob/09425c84e918c298909bcabd51bb9d9b0f88c0a9/server.js#L148
so perhaps it should be "https://blockbuilder.org/auth/github/callback" instead of "/auth/github/callback"

**Comment by enjalot** [comment]
This should work now, please confirm

**Comment by micahstubbs** [comment]
I am now able to log in with github on mobile Chrome. nice work @enjalot!

will close this one as fixed, and re-open if @curran @Fil or others report problems logging in later.
