### ISSUE TITLE
Authentification via github account does not work

### ISSUE THREAD

**Issue by EE2dev** [enjalot/blockbuilder#229]
I love to use blockbuilder and for me logging in through the github account works perfectly fine.
A friend of mine wanted to host a d3.js quiz I wrote, so I thought the easiest is
- he creates his own github account
- he just forkes my gist through blockbuilder
- he can adjust the code in blockbuilder

Logging on github works fine. But logging on blockbuilder.org through the github account leads to the following error:

![gh_bb](https://user-images.githubusercontent.com/7562919/48482725-c6ab4000-e811-11e8-8ad7-22213a3e1216.png)

![lnhmjjkcoaomllab](https://user-images.githubusercontent.com/7562919/48482568-500e4280-e811-11e8-81b1-a18778010fd9.png)

Do you need more than a github account to use blockbuilder and fork an existing gist? Do you need to have an existing github repo or a gist,..?!

**Comment by micahstubbs** [comment]
@EE2dev yikes, sorry that your friend hit this bug.  I'm going to combine the feedback here with https://github.com/enjalot/blockbuilder/issues/227
