### ISSUE TITLE
Bump magic-sandbox

### ISSUE THREAD

**Issue by curran** [enjalot/blockbuilder#241]
There's been a recent release of magic-sandbox that addresses a minor issue with HTTPS. I think it will make some non-working bl.ocks work again (that were probably working before HTTPS policies became more strict).

https://github.com/datavis-tech/magic-sandbox/releases/tag/v1.5.0

**Comment by micahstubbs** [comment]
will try to do this soon.  Thanks @curran for the upstream fix and creating this issue here.
