### ISSUE TITLE
Branding: blockbuilder vs building blocks

### ISSUE THREAD

**Issue by Fil** [enjalot/blockbuilder#89]
It's confusing. I think there is a need to chose one and forget the other — *blockbuilder* being the URL it is the natural candidate: :+1:

**Comment by enjalot** [comment]
I agree! I think we can settle on blockbuilder. altho I don't think I can
rename the repo easily? the kickstarter will also remain the same but thats
history now :)

On Thu, Dec 3, 2015 at 2:05 AM, Fil <notifications@github.com> wrote:

> It's confusing. I think there is a need to chose one and forget the other
> — blockbuilder being the URL it is the natural candidate: [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/enjalot/building-blocks/issues/89>.
>



-- 
Ian Johnson - 周彦
http://enja.org

**Comment by Fil** [comment]
/methinks you can rename the repo at
https://github.com/enjalot/building-blocks/settings

**Comment by enjalot** [comment]
done! easy enough. thanks :+1:
