### ISSUE TITLE
"fresh block" too easily MISunderstood

### ISSUE THREAD

**Issue by stelt** [enjalot/blockbuilder#91]
see http://bl.ocks.org/stelt/1eb554e5a523a5ec71e1 for suggestions

**Comment by georules** [comment]
Is the major change here a more visible color to see the size of the SVG element?  I feel that the shadowed border on blockbuilder and 1px border on blocks does this decently.  I'm not sure that "below" is needed - you can change anything.

@enjalot was discussing with me some ways he thought the fresh block could be better, that he often finds himself having to change the code to integrate with other projects. I can't remember exactly what part of it that concerned.

**Comment by stelt** [comment]
There's a few things that might put a beginner on the wrong foot:
- in CSS you define SVG to use 100% of the available HTML surface area, while a little lower in D3/js you define it to be a certain size of pixels
- the variable svg is not pointing to the svg element, but to a g element
- 2 values that are already available are calculated. (X-A-B)+A+B=X after all

**Comment by georules** [comment]
Good points.  I didn't understand that from your example.  +1 to reconsider this.

**Comment by enjalot** [comment]
I take your points. I've decided to simplify and forgo the margin convention. I feel like it adds a bunch of code that looks imposing and probably doesn't save that much time. I almost always delete it, I also don't want coding a chart to be the primary purpose of blockbuilder, which the default code implies.
