### ISSUE TITLE
Add manual vs automatic update option

### ISSUE THREAD

**Issue by mostaphaRoudsari** [enjalot/blockbuilder#93]
It's probably me being too old fashioned but as great as the auto update is, sometimes it can be very distracting. I think adding an option to lock the solver (i.e. stop live update) can be helpful. I can switch to manual mode, make couple of changes here and there and then see the update once.

**Comment by enjalot** [comment]
Thanks for submitting this! I've heard this before, and I've been thinking how often I've wished for this recently... I think I will try to add something like this soon:
![autoruna](https://cloud.githubusercontent.com/assets/96189/12042855/0b4a3c4a-ae4d-11e5-897d-01e938a9de1d.jpg)
![autorunb](https://cloud.githubusercontent.com/assets/96189/12044446/569fe426-ae5f-11e5-9b5e-e5a8299d0c84.jpg)

**Comment by mostaphaRoudsari** [comment]
Thanks. The drawing looks great! One question. Is that going to stay on top on line 1 and I need to scroll all the way to the top of the page each time that I want to turn it on/off?

**Comment by enjalot** [comment]
The plan is to keep the button fixed to the top of the editor. I will probably use this as a place to put more editor related controls as well.

**Comment by mostaphaRoudsari** [comment]
:+1:

**Comment by mostaphaRoudsari** [comment]
@enjalot it works perfect in side view mode but not in the standard mode

works here:
![image](https://cloud.githubusercontent.com/assets/2915573/12046433/d5ef9f92-ae86-11e5-9b7d-2fe126cf93d6.png)

but not here:
![image](https://cloud.githubusercontent.com/assets/2915573/12046423/b3a93466-ae86-11e5-8c76-04bebf8295c3.png)

**Comment by enjalot** [comment]
@mostaphaRoudsari in that second screenshot you have the renderer popped up over the editor. if you hit escape (or click the yellow) it will be visible again. The button is part of the editor UI which is why its being covered.
For now I didn't implement the sticky header when you scroll up, I figure the keyboard shortcut of Ctrl+P should serve as a quick way to avoid scrolling to the top.

**Comment by mostaphaRoudsari** [comment]
Hi @enjalot. Thank you for the clarification. Ctrl+P does all I need.

**Comment by georules** [comment]
:heart:
