### ISSUE TITLE
d3.xml not parsing xml

### ISSUE THREAD

**Issue by SpaceActuary** [enjalot/blockbuilder#94]
It doesn't appear that d3.xml is working in blockbuilder, although it does work on bl.ocks.

Compare:
http://bl.ocks.org/lgrammel/2772585
http://blockbuilder.org/lgrammel/2772585

Also:
http://bl.ocks.org/mbostock/ec585e034819c06f5c99
http://blockbuilder.org/mbostock/ec585e034819c06f5c99

Is there some sort of conflict between d3.xml and some of the other libraries?

**Comment by enjalot** [comment]
thanks so much for the repro cases, it helped me get to the bottom of the issue. When we load local files like `values.xml` I overried the XHR request and callback with the local files' contents. I wasn't accounting for the way XML is loaded, so I now properly set the responseXML of the simulated request.

thanks again!
